Configured the Git plugin with a XML template instead of groovy to avoid a sometimes occurring error "java.lang.NoClassDefFoundError: hudson/tasks/Mailer$UserProperty"